In [5]:
# Questão 1
RA = 11201721076
R1,R2,R3,R4 = 1,72,10,76
A = [[01.4,72.5],[10.9,76.7]]
A = np.array(A)

[[ 1.4 72.5]
 [10.9 76.7]]
[[ 80.75      -68.45     ]
 [ -6.8499985  -2.6500013]]


In [14]:
# a) (1,5) Calcule a DCT-2D através da equação de definição 2D, conforme a lista 1 de exercícios no Tidia4. Obs. Utilize duas casas decimais.
import numpy as np
# Definindo funções para a a dct 2d
def C(w,k):
    if w == 0:
        return (1/k)**(1/2)
    return (2/k)**(1/2)

def summation1(block,u,v):
    h,w = block.shape
    res = 0
    for x in range(w):
        for y in range(h):
            res+= block[x,y]* np.cos(((2*x+1)*u*np.pi)/(2*w))* np.cos(((2*y+1)*v*np.pi)/(2*h))
    return res

def F(block,u,v):
    h,w = block.shape
    return C(u,w)*C(v,h)*summation1(block,u,v)

def dct(block):
    block = np.float32(block)
    dctBlock = np.zeros(block.shape)
    h,w = block.shape
    for u in range(w):
        for v in range(h):
            dctBlock[u,v] = F(block,u,v)
    return np.float32(dctBlock) 

A_dct = dct(A)

# Print
print(A)
print(A_dct)

[[ 1.4 72.5]
 [10.9 76.7]]
[[ 80.75      -68.45     ]
 [ -6.8499985  -2.6500013]]


In [19]:
# b) (0,5) Com o valor obtido no item anterior, faça o arredondamento simples para um número inteiro (como a função round(.)), e calcule o erro quadrático médio da DCT deste bloco.
A_dct_round = np.round(A_dct)
print("A_dct_round")
print(A_dct_round)

def MSE(a,b):
    h,w = a.shape
    c = np.subtract(a,b)
    c = np.multiply(c,c)
    res = np.sum(c)/(h*w)
    return res

print("MSE entre imagem original e DCT")
print(MSE(A,A_dct))

print("\nMSE entre DCT e DCT arredondada")
print(MSE(A_dct,A_dct_round))

A_dct_round
[[ 81. -68.]
 [ -7.  -3.]]
MSE entre imagem original e DCT
8193.702322465184

MSE entre DCT e DCT arredondada
0.10249920189380646


In [20]:
# c) (0,5) Efetue a quantização dos coeficientes, obtendo o valor inteiro quantizado, através da tabela:
q = np.array([[5, 8],
              [8,12]])

# Quantização
def quantize(a,q):
    b = np.divide(a,q)
    b = np.round(b)
    return b

print(quantize(A_dct,q))

[[16. -9.]
 [-1. -0.]]


In [3]:
# Definindo funções para a a dct 2d inversa
def summation2(dctBlock,x,y):
    res = 0
    h,w = dctBlock.shape
    for u in range(w):
        for v in range(h):
            res_temp = C(u,w)*C(v,h)*dctBlock[u,v]
            res_temp*= np.cos(((2*x+1)*u*np.pi)/(2*w))* np.cos(((2*y+1)*v*np.pi)/(2*h))
            res+= res_temp
    return res

def dct_inv(dctBlock):
    dctBlock = np.float32(dctBlock)
    dctInvBlock = np.zeros(dctBlock.shape)
    h,w = dctBlock.shape
    for x in range(w):
        for y in range(h):
            dctInvBlock[x,y] = summation2(dctBlock,x,y)
    return np.float32(dctInvBlock)

In [15]:
# Mean Squared Error
def MSE(a,b):
    h,w = a.shape
    c = np.subtract(a,b)
    c = np.multiply(c,c)
    res = np.sum(c)/(h*w)
    return res

def PSNR(a,b): 
    mse = MSE(a,b)

    L = 255.0
    psnr = 20 * np.log10(L /np.sqrt(mse))
    return psnr

A_DCT  = np.array([[7.26,9.21],[9.14,11.59]])
A_DCT2 = np.array([[7,9],[9,12]])
print(MSE(A_DCT,A_DCT2))

0.07485000000000014


In [16]:
# Quantização
def quantize(a,q):
    b = np.divide(a,q)
    b = np.round(b)
    return b
q = np.array([[5,7],[7,8]])
print(quantize(A_DCT,q))

[[1. 1.]
 [1. 1.]]


In [17]:
# Questão 2
Y = [[20.4, 15.2, 29.1, 20.5],
    [17.3, 15.9, 31.2, 22.3],
    [15.2, 18.1, 17.0, 25.1],
    [20.8, 22.3, 18.7, 17.8]]
Y = np.array(Y)

# a)
Y_DCT_2x2 = np.zeros(Y.shape, dtype=np.float32)
for i in range(0,4,2):
    for j in range(0,4,2):
        Y_DCT_2x2[i:i+2,j:j+2] = dct(Y[i:i+2,j:j+2])

print(Y)
print(Y_DCT_2x2)

[[20.4 15.2 29.1 20.5]
 [17.3 15.9 31.2 22.3]
 [15.2 18.1 17.  25.1]
 [20.8 22.3 18.7 17.8]]
[[34.399998    3.2999997  51.55        8.750001  ]
 [ 1.2000003   1.9000001  -1.9499998  -0.15000057]
 [38.2        -2.2000003  39.3        -3.5999994 ]
 [-4.899999   -0.7000003   2.8000002  -4.500001  ]]


In [18]:
# b)
MSEs = np.zeros((2,2))
for i in range(0,4,2):
    for j in range(0,4,2):
        MSEs[int(i/2),int(j/2)] = MSE(Y[i:i+2,j:j+2], Y_DCT_2x2[i:i+2,j:j+2])
print(MSEs)

[[198.20498271 561.24748909]
 [532.64500394 517.7699924 ]]


In [19]:
# c)
Q = np.array([[5,15],[15,20]])

Y_DCT_Q = np.zeros(Y.shape)
for i in range(0,4,2):
    for j in range(0,4,2):
        Y_DCT_Q[i:i+2,j:j+2] = quantize(Y_DCT_2x2[i:i+2,j:j+2],q)
print(Y_DCT_Q)

[[ 7.  0. 10.  1.]
 [ 0.  0. -0. -0.]
 [ 8. -0.  8. -1.]
 [-1. -0.  0. -1.]]


In [20]:
# d)
Y_INV = np.zeros(Y.shape)

for i in range(0,4,2):
    for j in range(0,4,2):
        Y_INV[i:i+2,j:j+2] = dct_inv(Y_DCT_Q[i:i+2,j:j+2])
print(Y_INV)

[[3.5 3.5 5.5 4.5]
 [3.5 3.5 5.5 4.5]
 [3.5 3.5 3.  5. ]
 [4.5 4.5 4.  4. ]]


In [21]:
# e)
psnr = PSNR(Y,Y_INV)
print(psnr)

23.643634155605582


In [22]:
# Exercício 3
DCTY = [[353,-22],[-14,-10]]
DCTCb = [[266,8],[5,2]]
DCTCr = [[276,-1],[-1,3]]

In [23]:
# a)
DCTY_INV = dct_inv(DCTY)
DCTCb_INV = dct_inv(DCTCb)
DCTCr_INV = dct_inv(DCTCr)
print(np.array(DCTY))
print(DCTY_INV)

[[353 -22]
 [-14 -10]]
[[153.5 185.5]
 [177.5 189.5]]


In [24]:
# b)
def YCbCr2RGB(Y,Cb,Cr):
    Y = np.array(Y)
    Cb = np.array(Cb)
    Cr = np.array(Cr)

    R = 1.164*(Y-16)+1.596*(Cr-128)
    G = 1.164*(Y-16)-0.813*(Cr-128)-0.392*(Cb-128)
    B = 1.164*(Y-16)+2.017*(Cb-128)
    RGB = np.stack([R,G,B])
    return RGB
RGB = YCbCr2RGB(DCTY_INV,DCTCb_INV,DCTCr_INV)
print(RGB)

[[[176.808   210.864  ]
  [201.552   221.904  ]]

 [[146.61351 189.4075 ]
  [178.9195  191.9875 ]]

 [[185.2625  202.3405 ]
  [199.07951 200.94551]]]


In [26]:
# c)
#M_XYZ2sRGB = [[ 3.2405, -1.5371,-0.4985],
#              [-0.9693,  1.8760, 0.0416],
#              [ 0.0556, -0.2040, 1.0572]]
def XYZ2sRGB(XYZ):
    R = 3.2405*XYZ[0,:,:]-1.5371*XYZ[1,:,:]-0.4985*XYZ[2,:,:]
    G =-0.9693*XYZ[0,:,:]+1.8760*XYZ[1,:,:]+0.0416*XYZ[2,:,:]
    B = 0.0556*XYZ[0,:,:]-0.2040*XYZ[1,:,:]+1.0572*XYZ[2,:,:]
    return np.stack([R,G,B])

def sRGB2XYZ(RGB):
    X = 0.4125*RGB[0,:,:]+0.3576*RGB[1,:,:]+0.1804*RGB[2,:,:]
    Y = 0.2127*RGB[0,:,:]+0.7152*RGB[1,:,:]+0.0722*RGB[2,:,:]
    Z = 0.0193*RGB[0,:,:]+0.1192*RGB[1,:,:]+0.9503*RGB[2,:,:]
    return np.stack([X,Y,Z])
XYZ = sRGB2XYZ(RGB)
print(XYZ)

[[[158.78365 191.21576]
  [183.03575 196.44069]]

 [[155.84099 194.924  ]
  [185.20688 199.01672]]

 [[196.94366 218.93123]
  [214.40242 218.12617]]]


In [36]:
# d)
def gamma(channel):
    if channel<=0.0031308:
        return 12.92*channel
    return 1.055*np.power(channel,1/2.4)-0.055

def gamma_correction(RGB):
    R = gamma(RGB[0,:,:])
    G = gamma(RGB[1,:,:])
    B = gamma(RGB[2,:,:])
    return np.stack([R,G,B])
################################################
def gamma_inv(channel):
    h,w = channel.shape
    result = np.zeros([h,w])
    for i in range(w):
        for j in range(h):
            if channel[i,j]<=0.04045:
                result[i,j] = channel[i,j]/12.92
            result[i,j] = np.power(((channel[i,j]+0.055)/1.055),2.4)
    return result

def gamma_correction_inv(RGB):
    R = gamma_inv(RGB[0,:,:])
    G = gamma_inv(RGB[1,:,:])
    B = gamma_inv(RGB[2,:,:])
    return np.stack([R,G,B])

In [37]:
sRGB = gamma_correction_inv(RGB/255.0)
XYZ = sRGB2XYZ(sRGB)
print(XYZ)
# branco ???
# laranja ???

[[[0.37245689 0.55812015]
  [0.50658238 0.59479364]]

 [[0.33590277 0.54686483]
  [0.48835182 0.57430009]]

 [[0.50554267 0.63689577]
  [0.60824842 0.63161935]]]


In [41]:
# Exercício 4
# a)
H4 =   [[1,1,1,1],
        [1,1,-1,-1],
        [np.sqrt(2),-np.sqrt(2),0,0],
        [0,0,np.sqrt(2),-np.sqrt(2)]]
H4 = np.array(H4)/2
print(H4)
print(H4.T)
print(np.linalg.inv(H4))

[[ 0.5         0.5         0.5         0.5       ]
 [ 0.5         0.5        -0.5        -0.5       ]
 [ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678 -0.70710678]]
[[ 0.5         0.5         0.70710678  0.        ]
 [ 0.5         0.5        -0.70710678  0.        ]
 [ 0.5        -0.5         0.          0.70710678]
 [ 0.5        -0.5         0.         -0.70710678]]
[[ 0.5         0.5         0.70710678  0.        ]
 [ 0.5         0.5        -0.70710678  0.        ]
 [ 0.5        -0.5         0.          0.70710678]
 [ 0.5        -0.5        -0.         -0.70710678]]


In [ ]:
# T = HFH.T
# AB = BA = I
# Prove que H4.T = np.linalg.inv(H4)

In [44]:
# b)
# T = HFH.T
def Haar(F):
    H4F = np.matmul(H4,F)
    T = np.matmul(H4F,H4.T)
    return T
F =[[0,1,0,1],
    [1,0,1,0],
    [1,1,0,0],
    [0,0,1,1]]
F = np.array(F, dtype=np.float32)
T = Haar(F)

print(F)
print(T)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]]
[[ 2.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.         -1.         -1.        ]
 [ 0.          1.41421356  0.          0.        ]]
