In [3]:
import numpy as np

In [4]:
# Criando o bloco f
l1 = [128 for i in range(8)]
l2 = [-64 for i in range(8)]
f = [l1,l2,l2,l1,l1,l2,l2,l1]
f = np.array(f).T
print(f.shape, f)

(8, 8) [[128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]]


In [5]:
# Criando o bloco g
l3 = [32 for i in range(8)]
l4 = [-32 for i in range(8)]

g = [l3 if i % 2 == 0 else l4 for i in range(8)]
g = np.array(g)
print(g.shape, g)


(8, 8) [[ 32  32  32  32  32  32  32  32]
 [-32 -32 -32 -32 -32 -32 -32 -32]
 [ 32  32  32  32  32  32  32  32]
 [-32 -32 -32 -32 -32 -32 -32 -32]
 [ 32  32  32  32  32  32  32  32]
 [-32 -32 -32 -32 -32 -32 -32 -32]
 [ 32  32  32  32  32  32  32  32]
 [-32 -32 -32 -32 -32 -32 -32 -32]]


In [28]:
# Definindo funções para a a dct 2d
def C(w,k):
    if w == 0:
        return (1/k)**(1/2)
    return (2/k)**(1/2)

def summation1(block,u,v):
    h,w = block.shape
    res = 0
    for x in range(w):
        for y in range(h):
            res+= block[x,y]* np.cos(((2*x+1)*u*np.pi)/(2*w))* np.cos(((2*y+1)*v*np.pi)/(2*h))
    return res

def F(block,u,v):
    h,w = block.shape
    return C(u,w)*C(v,h)*summation1(block,u,v)

def dct(block):
    block = np.float32(block)
    dctBlock = np.zeros(block.shape)
    h,w = block.shape
    for u in range(w):
        for v in range(h):
            dctBlock[u,v] = F(block,u,v)
    return np.float32(dctBlock) 

In [29]:
# Definindo funções para a a dct 2d inversa (deve haver algum erro)
def summation2(dctBlock,x,y):
    res = 0
    h,w = dctBlock.shape
    for u in range(w):
        for v in range(h):
            res_temp = C(u,w)*C(v,h)*dctBlock[u,v]
            res_temp*= np.cos(((2*x+1)*u*np.pi)/(2*w))* np.cos(((2*y+1)*v*np.pi)/(2*h))
            res+= res_temp
    return res

def dct_inv(dctBlock):
    dctBlock = np.float32(dctBlock)
    dctInvBlock = np.zeros(dctBlock.shape)
    h,w = dctBlock.shape
    for x in range(w):
        for y in range(h):
            dctInvBlock[x,y] = summation2(dctBlock,x,y)
    return np.float32(dctInvBlock)

In [30]:
# Aplicando a dct e a dct inversa
f_dct = dct(f)
f_dct_inv = dct_inv(f_dct)

# Resultados
np.set_printoptions(precision=0, suppress=True)
print("f:"); print(f)
print("f_dct"); print(f_dct)
print("f_dct_inv"); print(f_dct_inv)

f:
[[128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]
 [128 -64 -64 128 128 -64 -64 128]]
f_dct
[[256.   0.  -0.  -0. 768.   0.  -0.  -0.]
 [ -0.   0.  -0.  -0.   0.  -0.   0.   0.]
 [  0.   0.  -0.  -0.  -0.   0.  -0.   0.]
 [  0.   0.   0.   0.   0.  -0.  -0.  -0.]
 [  0.  -0.  -0.   0.   0.   0.  -0.  -0.]
 [  0.   0.  -0.   0.   0.  -0.   0.   0.]
 [ -0.  -0.   0.  -0.  -0.   0.   0.  -0.]
 [ -0.   0.   0.   0.  -0.  -0.  -0.   0.]]
f_dct_inv
[[128. -64. -64. 128. 128. -64. -64. 128.]
 [128. -64. -64. 128. 128. -64. -64. 128.]
 [128. -64. -64. 128. 128. -64. -64. 128.]
 [128. -64. -64. 128. 128. -64. -64. 128.]
 [128. -64. -64. 128. 128. -64. -64. 128.]
 [128. -64. -64. 128. 128. -64. -64. 128.]
 [128. -64. -64. 128. 128. -64. -64. 128.]
 [128. -64. -64. 128. 128. -64. -64. 128.]]


In [31]:
# Aplicando a dct e a dct inversa
g_dct = dct(g)
g_dct_inv = dct_inv(g_dct)

# Resultados
np.set_printoptions(precision=0, suppress=True)
print("g:"); print(g)
print("g_dct"); print(g_dct)
print("g_dct_inv"); print(g_dct_inv)

g:
[[ 32  32  32  32  32  32  32  32]
 [-32 -32 -32 -32 -32 -32 -32 -32]
 [ 32  32  32  32  32  32  32  32]
 [-32 -32 -32 -32 -32 -32 -32 -32]
 [ 32  32  32  32  32  32  32  32]
 [-32 -32 -32 -32 -32 -32 -32 -32]
 [ 32  32  32  32  32  32  32  32]
 [-32 -32 -32 -32 -32 -32 -32 -32]]
g_dct
[[  0.   0.   0.   0.   0.   0.   0.  -0.]
 [ 46.   0.  -0.   0.   0.   0.  -0.  -0.]
 [  0.  -0.  -0.   0.   0.   0.  -0.   0.]
 [ 54.   0.  -0.   0.   0.   0.  -0.  -0.]
 [  0.   0.   0.   0.  -0.   0.   0.   0.]
 [ 81.   0.  -0.   0.   0.   0.  -0.  -0.]
 [  0.   0.   0.  -0.   0.  -0.   0.   0.]
 [232.   0.  -0.   0.   0.   0.  -0.  -0.]]
g_dct_inv
[[ 32.  32.  32.  32.  32.  32.  32.  32.]
 [-32. -32. -32. -32. -32. -32. -32. -32.]
 [ 32.  32.  32.  32.  32.  32.  32.  32.]
 [-32. -32. -32. -32. -32. -32. -32. -32.]
 [ 32.  32.  32.  32.  32.  32.  32.  32.]
 [-32. -32. -32. -32. -32. -32. -32. -32.]
 [ 32.  32.  32.  32.  32.  32.  32.  32.]
 [-32. -32. -32. -32. -32. -32. -32. -32.]]


In [32]:
# Exemplo da aula foi feito como teste de sanidade
h =[[63,  33,  36,  28,  63, 81,  86,  98],
    [ 27,  18,  17,  11,  22, 48, 104, 108],
    [ 72,  52,  28,  15,  17, 16,  47,  77],
    [132, 100,  56,  19,  10,  9,  21,  55],
    [187, 186, 166,  88,  13, 34,  43,  51],
    [184, 203, 199, 177,  82, 44,  97,  73],
    [211, 214, 208, 198, 134, 52,  78,  83],
    [211, 210, 203, 191, 133, 79,  74,  86]]
h = np.float32(h)

In [33]:
# Aplicando a dct e a dct inversa
h_dct = dct(h)
h_dct_inv = dct_inv(h_dct)

# Resultados
np.set_printoptions(precision=0, suppress=True)
print("h:"); print(h)
print("h_dct"); print(h_dct)
print("h_dct_inv"); print(h_dct_inv)

h:
[[ 63.  33.  36.  28.  63.  81.  86.  98.]
 [ 27.  18.  17.  11.  22.  48. 104. 108.]
 [ 72.  52.  28.  15.  17.  16.  47.  77.]
 [132. 100.  56.  19.  10.   9.  21.  55.]
 [187. 186. 166.  88.  13.  34.  43.  51.]
 [184. 203. 199. 177.  82.  44.  97.  73.]
 [211. 214. 208. 198. 134.  52.  78.  83.]
 [211. 210. 203. 191. 133.  79.  74.  86.]]
h_dct
[[ 720.  210.  104.  -69.   10.   20.  -12.    7.]
 [-327. -260.   67.   70.  -10.  -15.   21.    8.]
 [  93.  -84.  -66.   16.   24.   -2.   -5.    9.]
 [  89.   33.  -19.  -20.  -26.   21.   -3.    0.]
 [  -9.   42.   18.   27.   -7.  -17.   29.   -7.]
 [  -5.   15.  -10.   17.   32.  -15.   -4.    7.]
 [  10.    3.  -12.   -1.    2.    3.   -2.   -3.]
 [  12.   30.    0.   -3.   -3.   -6.   12.   -1.]]
h_dct_inv
[[ 63.  33.  36.  28.  63.  81.  86.  98.]
 [ 27.  18.  17.  11.  22.  48. 104. 108.]
 [ 72.  52.  28.  15.  17.  16.  47.  77.]
 [132. 100.  56.  19.  10.   9.  21.  55.]
 [187. 186. 166.  88.  13.  34.  43.  51.]
 [184. 203. 

In [37]:
# Lista para Prova 1
A = [[10.4,12.4],[14.9,20.4]]
A = np.array(A)

# Aplicando a dct e a dct inversa
A_dct = dct(A)
A_inv = dct_inv(A_dct)

# Print
print(A)
print(A_dct)
print(A_inv)

[[10. 12.]
 [15. 20.]]
[[29. -4.]
 [-6.  2.]]
[[10. 12.]
 [15. 20.]]


In [59]:
# Mean Squared Error
def MSE(a,b):
    h,w = a.shape
    c = np.subtract(a,b)
    c = np.multiply(c,c)
    res = np.sum(c)/(h*w)
    return res

def PSNR(a,b): 
    mse = MSE(a,b)

    L = 255.0
    psnr = 20 * np.log10(L /np.sqrt(mse))
    return psnr

A_DCT  = np.array([[7.26,9.21],[9.14,11.59]])
A_DCT2 = np.array([[7,9],[9,12]])
print(MSE(A_DCT,A_DCT2))
print(MSE3(A_DCT,A_DCT2))

0.07485000000000014
0.07485000000000014


In [43]:
# Quantização
def quantize(a,q):
    b = np.divide(a,q)
    b = np.round(b)
    return b
q = np.array([[5,7],[7,8]])
print(quantize(A_DCT,q))

[[1. 1.]
 [1. 1.]]


In [44]:
# Questão 2
Y = [[20.4, 15.2, 29.1, 20.5],
    [17.3, 15.9, 31.2, 22.3],
    [15.2, 18.1, 17.0, 25.1],
    [20.8, 22.3, 18.7, 17.8]]
Y = np.array(Y)

# a)
Y_DCT_2x2 = np.zeros(Y.shape, dtype=np.float32)
for i in range(0,4,2):
    for j in range(0,4,2):
        Y_DCT_2x2[i:i+2,j:j+2] = dct(Y[i:i+2,j:j+2])

print(Y)
print(Y_DCT_2x2)

[[20. 15. 29. 20.]
 [17. 16. 31. 22.]
 [15. 18. 17. 25.]
 [21. 22. 19. 18.]]
[[34.  3. 52.  9.]
 [ 1.  2. -2. -0.]
 [38. -2. 39. -4.]
 [-5. -1.  3. -5.]]


In [46]:
# b)
MSEs = np.zeros((2,2))
for i in range(0,4,2):
    for j in range(0,4,2):
        MSEs[int(i/2),int(j/2)] = MSE(Y[i:i+2,j:j+2], Y_DCT_2x2[i:i+2,j:j+2])
print(MSEs)

[[198. 561.]
 [533. 518.]]


In [47]:
# c)
Q = np.array([[5,15],[15,20]])

Y_DCT_Q = np.zeros(Y.shape)
for i in range(0,4,2):
    for j in range(0,4,2):
        Y_DCT_Q[i:i+2,j:j+2] = quantize(Y_DCT_2x2[i:i+2,j:j+2],q)
print(Y_DCT_Q)

[[ 7.  0. 10.  1.]
 [ 0.  0. -0. -0.]
 [ 8. -0.  8. -1.]
 [-1. -0.  0. -1.]]


In [48]:
# d)
Y_INV = np.zeros(Y.shape)

for i in range(0,4,2):
    for j in range(0,4,2):
        Y_INV[i:i+2,j:j+2] = dct_inv(Y_DCT_Q[i:i+2,j:j+2])
print(Y_INV)

[[4. 4. 6. 4.]
 [4. 4. 6. 4.]
 [4. 4. 3. 5.]
 [4. 4. 4. 4.]]


In [60]:
# e)
psnr = PSNR(Y,Y_INV)
print(psnr)

23.643634155605582


In [27]:
print(Y)
for i in range(0,4,2):
    for j in range(0,4,2):
        print(Y[i:i+2,j:j+2])

[[20. 15. 29. 20.]
 [17. 16. 31. 22.]
 [15. 18. 17. 25.]
 [21. 22. 19. 18.]]
[[20. 15.]
 [17. 16.]]
[[29. 20.]
 [31. 22.]]
[[15. 18.]
 [21. 22.]]
[[17. 25.]
 [19. 18.]]
