# Prova 2 b: Questão 5

In [8]:
import numpy as np

RA = 11201721076
R1 = 11
R2 = 20
R3 = 17
R4 = 21

X = [-0.1587, 0.1195, -0.2520, 0.0171, 1.2162, -1.6117, 0.1983, -0.9080, 1.4386, 0.8024, -1.6272, 0.0459, -0.5898, 0.5891, 0.1483, -0.1429]

## 5.a) (0,5) Determine a autocorrelação do intervalo i= 1, 2, 3 e 4, para m= 0, 1, 2 e 3, para o cálculo de um modelo LPC de ordem p=3.

In [9]:
# Definição de funções
def get_r(I,m,p,X, debug=0):
    '''
    I = vetor de indices
    m = Profundidade
    p = ordem
    '''
    r = []
    for i in range(0,max(I)):
        ri = 0
        if debug: print("r[",i,"] =",end="", sep="")
        for j in I:
            if j+i>max(I):
                break
            if debug: print(" + X[",j,"]*X[",j,"+",i,"]",end="",sep="")
            #print(X[j],"*",X[j+i])
            ri += X[j]*X[j+i]
        if debug: print()
        r.append(ri)
    return np.float64(r).reshape((1,len(I)))

In [10]:
# Autocorrelação
I = [1,2,3,4]
m = 3
p = 3

r = get_r(I,m,p,X,debug=True)
print("Vetor de autocorrelação r:")
print(r)

r[0] = + X[1]*X[1+0] + X[2]*X[2+0] + X[3]*X[3+0] + X[4]*X[4+0]
r[1] = + X[1]*X[1+1] + X[2]*X[2+1] + X[3]*X[3+1]
r[2] = + X[1]*X[1+2] + X[2]*X[2+2]
r[3] = + X[1]*X[1+3]
Vetor de autocorrelação r:
[[ 1.5572191  -0.01362618 -0.30443895  0.1453359 ]]


## 5.b) (0,5) Escreva a formulação do problema dos coeficientes de predição com os valores da matriz de autocorrelação (equações normais, ou Yule-Walker);

#### Formulação do problema:
$Ra = -r' $<br>
$a = R^{-1} {-r'}$

#### Em termos de variáveis:
a = R_inv r_prime_minus

In [11]:
# Definição de Funções
def get_R(I,m,p,X,debug=0):
    r = get_r(I,m,p,X)
    R = np.zeros([m,m])
    if debug: print("R =")
    for i in range(m):
        for j in range(m):
            if debug: print(" r[",abs(i-j),"]",end="", sep="")
            R[i,j] = r[0,abs(i-j)]
        print()
    return R

def get_r_prime(I,m,p,X,debug=0):
    r = get_r(I,m,p,X)

    if debug: 
        print("r_prime = [[",end="", sep="")
        [print(" r[",i,"]",end="", sep="") for i in range(1,m+1)]
        print(" ]].Transposed")

    r_prime = r[:,1:m+1].T
    return r_prime

In [12]:
R = get_R(I,m,p,X,1)
print("R = \n", R,"\n")


R_inv = np.linalg.inv(R)
print("R_inv = \n", R_inv)

R =
 r[0] r[1] r[2]
 r[1] r[0] r[1]
 r[2] r[1] r[0]
R = 
 [[ 1.5572191  -0.01362618 -0.30443895]
 [-0.01362618  1.5572191  -0.01362618]
 [-0.30443895 -0.01362618  1.5572191 ]] 

R_inv = 
 [[0.6677661  0.00698606 0.13061052]
 [0.00698606 0.64229265 0.00698606]
 [0.13061052 0.00698606 0.6677661 ]]


In [13]:
r_prime = get_r_prime(I,m,p,X,1)
print("r_prime = \n",r_prime,"\n")

print("r_prime_minus = -r_prime")
r_prime_minus = -r_prime 
print("r_prime_minus = \n",r_prime_minus)

r_prime = [[ r[1] r[2] r[3] ]].Transposed
r_prime = 
 [[-0.01362618]
 [-0.30443895]
 [ 0.1453359 ]] 

r_prime_minus = -r_prime
r_prime_minus = 
 [[ 0.01362618]
 [ 0.30443895]
 [-0.1453359 ]]


In [16]:
print("a = np.matmul(R_inv, r_prime_minus)")
a = np.matmul(R_inv, r_prime_minus)
print("a = \n", a)

a = np.matmul(R_inv, r_prime_minus)
a = 
 [[-0.00775647]
 [ 0.19461877]
 [-0.09314384]]


## 5.c) (0,5) Resolva o problema pela inversão da matriz de autocorrelação, calculando os coeficientes LPC, a= {a1, a2, a3}T.

In [17]:
a1 = a[0]
a2 = a[1]
a3 = a[2]

print("a1 =", a1)
print("a2 =", a2)
print("a3 =", a3)

a1 = [-0.00775647]
a2 = [0.19461877]
a3 = [-0.09314384]
